# Generated by Django 4.0.3 on 2024-01-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='nombre_servcio',
            new_name='nombre_servicio',
        ),
    ]
