# Generated by Django 4.0.3 on 2024-01-27 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0002_rename_nombre_servcio_servicio_nombre_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='key_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_veterinaria.estado'),
        ),
    ]
