# Generated by Django 4.0.3 on 2024-01-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0003_servicio_key_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='dni',
            field=models.TextField(blank=True, null=True),
        ),
    ]
