# Generated by Django 4.0.3 on 2024-01-28 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0005_tiposervicio_servicio_key_tipo_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='key_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_veterinaria.estado'),
        ),
    ]
