# Generated by Django 4.0.3 on 2024-01-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0006_tiposervicio_key_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='sexo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
