# Generated by Django 4.0.3 on 2024-01-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0007_cliente_sexo_veterinario_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='num_cel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
