# Generated by Django 4.0.3 on 2024-01-29 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0008_alter_cliente_num_cel'),
    ]

    operations = [
        migrations.AddField(
            model_name='raza',
            name='key_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_veterinaria.estado'),
        ),
    ]
