# Generated by Django 4.0.3 on 2024-01-30 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0012_tipocita_delete_programacioncita_cita_key_tipo_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocita',
            name='key_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_veterinaria.estado'),
        ),
    ]
