# Generated by Django 4.0.3 on 2024-01-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0013_tipocita_key_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_fin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_inicio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
