# Generated by Django 4.0.3 on 2024-01-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0014_cita_fecha_inicio_cita_hora_fin_cita_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo_consulta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
