# Generated by Django 4.0.3 on 2024-01-30 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0015_cita_motivo_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='key_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_veterinaria.servicio'),
        ),
    ]
