# Generated by Django 4.0.3 on 2024-02-10 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0017_cita_motivo_cancelacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaFrecuentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('key_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_veterinaria.estado')),
            ],
            options={
                'db_table': 'pregunta_frecuente',
            },
        ),
    ]
