# Generated by Django 4.0.3 on 2024-02-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0019_menu_asignacionpermiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipousuario',
            name='action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
