# Generated by Django 4.0.3 on 2024-02-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0021_usuario_key_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
