# Generated by Django 4.0.3 on 2024-02-13 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0023_usuario_num_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionpermiso',
            name='key_usuario',
        ),
        migrations.AddField(
            model_name='asignacionpermiso',
            name='key_tipo_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_veterinaria.tipousuario'),
        ),
    ]
