# Generated by Django 4.0.3 on 2024-02-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0024_remove_asignacionpermiso_key_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_session',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
