# Generated by Django 4.0.3 on 2024-02-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0025_usuario_fecha_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='num_documento',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
