# Generated by Django 4.0.3 on 2024-02-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0026_alter_usuario_num_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='token',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='token_recup',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
    ]
