# Generated by Django 4.0.3 on 2024-02-13 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0027_remove_usuario_apellido_remove_usuario_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='key_usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
