# Generated by Django 4.0.3 on 2024-02-13 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0029_usuario_log_key_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='num_documento',
            new_name='document_number',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='key_tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='userType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_veterinaria.tipousuario'),
        ),
    ]
