# Generated by Django 4.0.3 on 2024-02-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0031_usuario_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='userType',
            new_name='user_type',
        ),
    ]
