# Generated by Django 4.0.3 on 2024-02-14 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0033_alter_usuario_groups_alter_usuario_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
