# Generated by Django 4.0.3 on 2024-02-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0035_permiso_asignacionpermiso_key_permiso'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permiso',
            table='permiso',
        ),
    ]
