# Generated by Django 4.0.3 on 2024-02-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0038_remove_receta_key_medicamento_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detalle_receta',
            table='detalle_receta',
        ),
    ]
