# Generated by Django 4.0.3 on 2024-02-18 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0039_alter_detalle_receta_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='diganostico',
            new_name='diagnostico',
        ),
    ]
