# Generated by Django 4.0.3 on 2024-05-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_veterinaria', '0041_restablerusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tiempo_estimado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
